### ISSUE TITLE
still updating?

### ISSUE THREAD

**Issue by m4d3bug** [enthus1ast/nimMime#1]
smtp module doesn't support threads. #9728
Andreas just fix this bug last week,your code still updating?

**Comment by enthus1ast** [comment]
this project is quite abandoned (i've left the company where i used this). Maybe i should take the time to bring the email attachement code in a better shape. Then maybe make a pr only for smtp.nim

do you use it? If yes then i'll try to fix the bugs you have.

**Comment by m4d3bug** [comment]
yes,i am going to use it in my project,it will be helpful.
we are using dev branch in nim 0.19.9.

**Comment by enthus1ast** [comment]
i'll test it soon with the newest nim version. Feel free to open issues though.

**Comment by m4d3bug** [comment]
fine,waiting your code,if have .nimble will be great and official.

**Comment by lbcheng888** [comment]
@enthus1ast Thanks for your devoting, the issue we are facing is email body is missing when there are attachments.

**Comment by enthus1ast** [comment]
i'm just guessing here but, when you attach attachments/other mime messages, then the message ist automatically (tm) upgraded to a multipart message, in multipart, the body is just a reminder to old email clients that this is a multipart msg (which should not be displayed by new clients). 
So your email body should be  in a new `newMimeMessage` which must be attached to the envelope. See https://github.com/enthus1ast/nimMime/blob/master/mime.nim#L481

**Comment by m4d3bug** [comment]
other way,the line 19 of mime.nim might need some change?
```
  ContentTransferEncoders* = enum 
```
It look like cause the example code trun some wrong about BASE64 & QUOTED-PRINTABLE

**Comment by m4d3bug** [comment]
still checking your code,does newMimeMessage is encode by base64 automatically?

**Comment by ThomasTJdev** [comment]
@enthus1ast any plans on making a nimble package out of this repo?

**Comment by enthus1ast** [comment]
> other way,the line 19 of mime.nim might need some change?
> 
> ```
>   ContentTransferEncoders* = enum 
> ```
> 
> It look like cause the example code trun some wrong about BASE64 & QUOTED-PRINTABLE

@m4d3bug if this is still relevant, could you please describe this in a new issue?
(closing this for now)
