### ISSUE TITLE
Nimble library and cleanup

### ISSUE THREAD

**Issue by ThomasTJdev** [enthus1ast/nimMime#2]
Hi @enthus1ast 

Do you have any plans for updating the code and making it a Nimble package? I have forked the packaged, removed unused code and added a `nimble` file. Are you interested in PR's?

https://github.com/ThomasTJdev/nimMime

**Comment by enthus1ast** [comment]
Sure feel free!
I'm still a little unsure of the overall design and I think this needs an overhaul to be really usable.

**Comment by ThomasTJdev** [comment]
Cool, I'll take a look at it. What license are you going with?

**Comment by enthus1ast** [comment]
> Cool, I'll take a look at it. What license are you going with?

MIT

The issue I had with my implementation was that the encoder procs changed the message. Maybe it would be better to just save the desired encoding somewhere and encode everythig on a finalize step.
Maybe the "finalize" could also be done at '$' . Back then I just needed it to work, not to be pretty :)

**Comment by ThomasTJdev** [comment]
Hi @enthus1ast 

I can see, that I'll take me more time than expected to help you.. I have only cleaned up the package a bit and made it ready to be a Nimble package - no optimizing or improvement. Let me know, if you still would like it as a PR.

Even though there's still some outstanding elements, I think you should publish it as a Nimble package - I haven't found any other package, which enables attachments.

**Comment by enthus1ast** [comment]
sure make pr. 
thank you for taking the time to clean it up @ThomasTJdev 

the points i brought up where rather loud thinking.

**Comment by enthus1ast** [comment]
thank you @ThomasTJdev 
i eventually fix the things that bugs me with my implementation in other issues, closing this for now.
